version: '3.4'

services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD=postgrespw
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postresql/data
    command: -p 5433
    networks:
      custom:

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
    networks:
      custom:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      custom:

  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile

  searchservice:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: src/SearchSerivce/Dockerfile

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile

  gatewayservice:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile

  biddingservice:
    image: ${DOCKER_REGISTRY-}biddingservice
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile

  web-app:
    image: ${DOCKER_REGISTRY-}web-app
    build: 
      context: .
      dockerfile: frontend/web-app/Dockerfile
    volumes:
      - webdata:/var/lib/web/data
    #ports:
    #  - "3000:3000"
    extra_hosts:
      - id.carsties.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=somethingreallyreallysecret
      - NEXTAUTH_URL=http://app.carsties.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gatewayservice/
      - ID_URL=http://id.carsties.com
      - NEXT_PUBLIC_NOTIFY_URL=http://gatewayservice/notifications
      - VIRTUAL_HOST=app.carsties.com
      - VIRTUAL_PORT=3000
    networks:
      custom:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      custom:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs

volumes:
  pgdata:
  mongodata:
  webdata:





