version: '3.4'

services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_PASSWORD=postgrespw
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postresql/data
    command: -p 5433
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  #auctionservice:
  #  image: ${DOCKER_REGISTRY-}auctionservice
  #  build:
  #    context: .
  #    dockerfile: src/AuctionService/Dockerfile

  #search:
  #  image: ${DOCKER_REGISTRY-}searchservice
  #  build:
  #    context: .
  #    dockerfile: src/SearchService/Dockerfile

volumes:
  pgdata:
  mongodata:

