version: '3.4'

#services:
  #auctionservice:
  #  container_name: auctionservice
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ConnectionStrings__DefaultConnection=Server=postgres:5433;User Id=postgres;Password=postgrespw;Database=auctions
  #  ports:
  #    - "7001:80"
